language: python
python: 3.5
os:
  - linux
#  - osx
env:
  - TOX_ENV=py27-aws
  - TOX_ENV=py27-openstack
  - TOX_ENV=py35-aws
  - TOX_ENV=py35-openstack
  - TOX_ENV=pypy-aws
  - TOX_ENV=pypy-openstack
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
